apiVersion: apps/v1
kind: Deployment
metadata:
  name: koomzoaksdemo-app-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koomzoaksdemo-app
  template:
    metadata:
      labels:
        app: koomzoaksdemo-app
    spec:
      containers:
        - name: koomzoaksdemo-container
          image: koomzoaks.azurecr.io/aksnet:v0.0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: koomzoaksdemo-service
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: koomzoaksdemo-app